### ISSUE TITLE
Backend: Socal media page

### ISSUE THREAD

**Issue by gourango** [MikrosKosmos/Photocast#12]
1. Brand or Photographer name will display
2. Like, Comment, reply, rating, bookmark, total view, add to kart
3. The only partner can upload a photo, customer don't have the right to upload the photos

**Comment by Pronoy999** [comment]
It will take time, I will have to create a new microservice.

**Comment by Pronoy999** [comment]
It is not possible to implement view count, I can implement like count.

**Comment by gourango** [comment]
Ok
